### ISSUE TITLE
服务器启动报错

### ISSUE THREAD

**Issue by YatsukiRenka** [eeg1412/wikimoeCardByNodeJS#12]
大佬你好，今天偶然看到了这个游戏感觉非常有意思，想试一下自己搭一个

在进行完使用方法的第4步之后，启动服务器时报错

>[root@server]# npm start
>
> wikimoecard@2.3.1 start /root/server
> nodemon --delay 60 -e pem,key --watch bin ./bin/www
>
>[nodemon] 1.19.4
>[nodemon] to restart at any time, enter `rs`
>[nodemon] watching dir(s): bin/**/*
>[nodemon] watching extensions: pem,key
>[nodemon] starting `node ./bin/www`
>/root/server/bin/www:46
>io.on('connection', async (socket) => {
>                          ^
>
>SyntaxError: Unexpected token (
>    at createScript (vm.js:56:10)
>    at Object.runInThisContext (vm.js:97:10)
>    at Module._compile (module.js:549:28)
>    at Object.Module._extensions..js (module.js:586:10)
>    at Module.load (module.js:494:32)
>    at tryModuleLoad (module.js:453:12)
>    at Function.Module._load (module.js:445:3)
>    at Module.runMain (module.js:611:10)
>    at run (bootstrap_node.js:394:7)
>    at startup (bootstrap_node.js:160:9)
>[nodemon] app crashed - waiting for file changes before starting...

请问一下这是什么问题……？之前没有用过nodejs所以挺茫然的，求大佬赐教（

**Comment by eeg1412** [comment]
这看起来是个语法错误？你之前都改动了什么文件？

**Comment by YatsukiRenka** [comment]
没有改动除了default.js里面【网页端口】和【mongoDB地址】之外的任何文件……我尝试了一下重新下载code，依然不行

**Comment by YatsukiRenka** [comment]
![image](https://user-images.githubusercontent.com/38554950/77027267-b50f1500-69d0-11ea-8abb-669a548c9ffb.png)
箭头是这么指向的

**Comment by eeg1412** [comment]
@YatsukiRenka 可以将你改动后的文件代码贴上来看看吗？

**Comment by YatsukiRenka** [comment]
啊找到问题了……nodejs的版本太久，升级后已经OK了，感谢大佬
