### ISSUE TITLE
制卡功能无法加载出来

### ISSUE THREAD

**Issue by YatsukiRenka** [eeg1412/wikimoeCardByNodeJS#13]
@eeg1412 大佬你好……又来打扰了
制卡功能好像加载不出来……
你的站点那边也是，一样加载不出制卡界面，上传图片之后始终是空白的

**Comment by eeg1412** [comment]
@YatsukiRenka 这种一般是因为浏览器不支持webgl，或者电脑配置问题。一般linux的浏览器默认是关闭的。你可以搜索引擎搜索下如何开启浏览器的webgl功能。

**Comment by YatsukiRenka** [comment]
@eeg1412 可以用了，谢谢大佬
