### ISSUE TITLE
安装过程中出现两个问题

### ISSUE THREAD

**Issue by HCLonely** [eeg1412/wikimoeCardByNodeJS#3]
1. api.js第11行大小写错了`var apiSendMail = require('../api/sendEMail');`,api目录里的文件名为`sendEmail.js`;
2. 缺少js文件`app.361fbb4.js`.

**Comment by eeg1412** [comment]
@HCLonely 非常感谢，这两个问题在[v1.1.7](https://github.com/eeg1412/wikimoeCardByNodeJS/releases/tag/v1.1.7)中已经修复了！
