### ISSUE TITLE
矿场功能增加建议

### ISSUE THREAD

**Issue by CodeCRH** [eeg1412/wikimoeCardByNodeJS#9]
1.增加道具，广树力场，效果（当力场范围内被保罗炸弹炸到时，释放广树力场者获得一定收益，被稿子挖取格子，则无效果凭白消耗）
目标：形成镐子、保罗炸弹、广树力场的三角动态制衡，和心理博弈

在上一条的基础上
2.增加保罗炸弹炸掉的星星排行和广树力场得到收益的排行，用于对照玩家心理博弈的结果

3.若1可实行，可降低保罗炸弹范围为一个十字，避免广树力场非常容易被炸到的问题

**Comment by Dreamer-Paul** [comment]
很明显，这个功能的目的就是想继续增加星星收益！不用伪装了，都知道了
